"""Auto-generierte Lore (Icon + Flavor-Text „Symbolik") je Achievement — WoW-Stil.
Generiert per Loremaster-Workflow; von achievements.py optional geladen."""

LORE = {
    "all_months": {"icon": "🌙", "flavor": "Von Januar bis Dezember schon mal gelaufen – die Jahreskarte vollständig gestempelt."},
    "all_weekdays": {"icon": "📆", "flavor": "Montag bis Sonntag, alle einmal erobert – der Wochenkalender kennt dich."},
    "attack": {"icon": "⚔️", "flavor": "Ein Kilometer wie ein Ausfallschritt mitten im Gefecht – die anderen sehen nur Staub."},
    "cb_14": {"icon": "🩹", "flavor": "Nach zwei Wochen Pause zurück auf die Straße. Rost abgeklopft, weitergelaufen."},
    "cb_60": {"icon": "🐦‍🔥", "flavor": "Aus der Asche von sechzig Tagen Stille steigt ein neuer Lauf empor."},
    "cb_rhythm": {"icon": "🎯", "flavor": "Nach dem Comeback gleich vier Wochen durchgehalten — der Rhythmus ist zurück und bleibt."},
    "cb_x3": {"icon": "🔁", "flavor": "Dreimal gefallen, dreimal wieder aufgestanden — im selben Jahr. Ausdauer zeigt sich auch abseits der Strecke."},
    "cd_ampm": {"icon": "🌅", "flavor": "Vor der Sonne wach, nach der Sonne noch aktiv – ein Tag, gezähmt von beiden Enden der Uhr."},
    "cd_cross4": {"icon": "🔀", "flavor": "Vier Wochen konstante Vielfalt – die Disziplin eines Champions, die Routine eines Uhrwerks."},
    "cd_double": {"icon": "🌗", "flavor": "Zwei Sessions, ein Tag. Der Körper ächzt, doch die Statistik jubelt."},
    "cd_form_km": {"icon": "📈", "flavor": "Acht Wochen wachsende Kilometer bei stabiler Waage – der seltene Beweis, dass Fortschritt kein Zufall ist."},
    "cd_fullbody": {"icon": "🏋️", "flavor": "Lauf, Kraft und 70.000 Schritte in einer Woche – dein Körper hat diese Woche nichts ausgelassen."},
    "cd_run_str": {"icon": "🤺", "flavor": "Beine und Eisen am selben Tag bezwungen — ein Duell, das nur ein Sieger übersteht."},
    "cd_str25": {"icon": "🏆", "flavor": "25 Tage im Doppelpack aus Schweiß und Stahl — Sammlerstück für die wahrhaft Verbissenen."},
    "cd_triath": {"icon": "🔱", "flavor": "Laufen, Radeln, Stemmen — an einem einzigen Tag drei Disziplinen gebändigt wie ein wahrer Dreikämpfer."},
    "cd_triweek": {"icon": "🥉", "flavor": "Wer Laufen, Kraft und Rad in einer Woche vereint, hat den Dreiklang gemeistert – noch kein Solo, aber ein feines Trio."},
    "cd_variety": {"icon": "🎲", "flavor": "Drei Sportarten, eine Woche – der Beweis, dass Abwechslung mehr ist als eine Ausrede fürs Nichtstun."},
    "cnt_1": {"icon": "🐣", "flavor": "Der erste Lauf. Klein, wacklig, aber der Ursprung von allem, was noch kommt."},
    "cnt_10": {"icon": "🧦", "flavor": "10 Läufe – die Schuhe riechen jetzt eindeutig nach Gewohnheit."},
    "cnt_100": {"icon": "💎", "flavor": "Hundert Läufe geschliffen wie ein Edelstein aus reiner Ausdauer."},
    "cnt_25": {"icon": "🌱", "flavor": "25 Läufe. Aus dem Versuch ist ein Ritual gewachsen."},
    "cnt_250": {"icon": "👑", "flavor": "250 Läufe. Man nennt dich nicht mehr Läufer – man nennt dich Besessenheit in Bewegung."},
    "cnt_50": {"icon": "💧", "flavor": "50 Läufe – ein halbes Hundert Schweißperlen auf dem Weg zur Legende."},
    "day_streak_10": {"icon": "⏱️", "flavor": "Zehn Tage ohne Pause. Der Kalender hat aufgehört, dich zu überraschen."},
    "day_streak_7": {"icon": "🔥", "flavor": "Sieben Tage in Folge — die Straßen kennen bereits deinen Schritt."},
    "days_100": {"icon": "📅", "flavor": "Hundert Tage, an denen die Straße dich rief und du geantwortet hast."},
    "days_200": {"icon": "🗓️", "flavor": "Ein seltener Kalender voller Fußabdrücke – die Konsistenz eines wahren Veteranen."},
    "days_365": {"icon": "🗓️", "flavor": "365 Tage, ein Jahr Umlauf um die Sonne – und du, treu wie der Kalender selbst."},
    "dist_10": {"icon": "👟", "flavor": "Zweistellig, zweifach stolz. Der Beginn zählt doppelt."},
    "dist_15": {"icon": "🌤️", "flavor": "Die Sonne steht schon tiefer, doch deine Beine tragen noch. Fortschritt riecht nach Asphalt."},
    "dist_16": {"icon": "🧭", "flavor": "Zehn Meilen im alten Maß, gemessen von Läufern, die keine Kilometer kannten."},
    "dist_20": {"icon": "🛡️", "flavor": "Wer die 20 durchsteht, trägt fortan das Abzeichen der Unbeugsamen."},
    "dist_25": {"icon": "🔮", "flavor": "Ein Blick über den Horizont der Normalität — die Ultra-Schatten winken bereits."},
    "dist_30": {"icon": "🚧", "flavor": "Die Grenze, an der viele umkehren. Du bist einfach weitergelaufen."},
    "dist_35": {"icon": "🔥", "flavor": "Hier beginnt das Ultra-Land, wo Normalsterbliche längst zu Hause geblieben wären."},
    "dist_5": {"icon": "🥾", "flavor": "Ein bescheidener Anfang. Selbst Legenden mussten irgendwo die Schuhe schnüren."},
    "dist_50": {"icon": "⚔️", "flavor": "Jenseits des Marathons wartet nur noch der eigene Kopf als Gegner — und du hast gewonnen."},
    "dist_80": {"icon": "🌋", "flavor": "80,5 km durch Nacht, Zweifel und Blasen. Wenige erzählen diese Saga aus erster Hand."},
    "dist_hm": {"icon": "🏅", "flavor": "21,0975 km reiner Wille. Das Volk der Halbmarathonis erhebt sein Glas."},
    "dist_hm10": {"icon": "🏰", "flavor": "Zehn Halbmarathons erbauen eine Festung aus Ausdauer, die niemand mehr einreißt."},
    "dist_hm5": {"icon": "🧵", "flavor": "Fünf Halbmarathons, ein roter Faden aus Schweiß und Sturheit."},
    "dist_m3": {"icon": "🗿", "flavor": "Drei Marathons — Monumente, die man nicht dem Zufall verdankt, sondern dem Training."},
    "dist_marathon": {"icon": "👑", "flavor": "42,195 km — die Zahl, die Mythen schrieb. Pheidippides würde applaudieren, hätte er noch Atem."},
    "dist_pr": {"icon": "📈", "flavor": "Deine eigene Bestmarke, erneut zerschmettert. Der einzige Gegner, der immer mitläuft, bist du."},
    "dist_round": {"icon": "🎯", "flavor": "Exakt getroffen wie ein Pfeil ins Zentrum — Zahlenmagie für Ordnungsliebende."},
    "doppelpack": {"icon": "👟", "flavor": "Zweimal am selben Tag die Schuhe geschnürt – warum einmal, wenn's auch doppelt geht."},
    "dur_120": {"icon": "⌛", "flavor": "Zwei Stunden Dauerbetrieb. Die innere Stimme, die aufhören will, hat verloren."},
    "dur_180": {"icon": "🌌", "flavor": "Drei Stunden zwischen Wahnsinn und Erleuchtung. Nur wenige Sterbliche kehren mit Geschichten zurück."},
    "dur_90": {"icon": "⏳", "flavor": "Neunzig Minuten im eigenen Kopf spazieren gehen. Manche nennen es Meditation, du nennst es Training."},
    "dur_round": {"icon": "⏱️", "flavor": "Selten trifft ein Läufer die Zeit so exakt wie einen Pfeil ins Schwarze."},
    "early_series": {"icon": "🌅", "flavor": "Vier Läufe zur gleichen Stunde gestartet — die Morgendämmerung kennt schon deinen Namen."},
    "ef_1": {"icon": "👟", "flavor": "Ein Meter, ein Herzschlag – die Grundrechenart jedes Läufers, brav erlernt und sauber vollbracht."},
    "ef_11": {"icon": "🎯", "flavor": "Das Herz trifft mit weniger Schlägen mehr Strecke – ein Zeichen wachsender Treffsicherheit."},
    "ef_12": {"icon": "💎", "flavor": "Geschliffen wie ein Edelstein – jeder Herzschlag trägt nun spürbar mehr Weg auf seinen Facetten."},
    "ef_13": {"icon": "🦌", "flavor": "Leichtfüßig wie ein Hirsch durch den Wald – dieses Herz verschwendet keinen einzigen Schlag mehr."},
    "ef_pr": {"icon": "🏆", "flavor": "Ein neuer Bestwert im stillen Wettstreit des eigenen Herzens gegen sich selbst."},
    "ef_rise4": {"icon": "🌊", "flavor": "Vier Wochen stetig steigende Ebbe im Pulsschlag – die Flut der Fitness zieht sich zuverlässig zurück."},
    "even_month": {"icon": "⚖️", "flavor": "Ein ganzer Monat im perfekten Gleichschritt – Metronom statt Muskelkater."},
    "fit_all": {"icon": "👑", "flavor": "Drei Trends, ein Urteil: besser. Kein Zufall mehr, sondern Beweis. Legenden werden aus solchen Wochen gemacht."},
    "fit_double": {"icon": "🍀", "flavor": "Schneller UND ruhiger im Puls — die seltene Kombo, die zeigt: der Körper lernt wirklich dazu."},
    "fit_easy": {"icon": "🕊️", "flavor": "Im lockeren Trab wird das Herz zur Taube – ruhiger im Flug, obwohl das Tempo unverändert bleibt."},
    "fit_pah": {"icon": "🐆", "flavor": "Gleicher Puls, doch der Gepard in dir hat gelernt, schneller zu jagen – ein Fortschritt jenseits des Zufalls."},
    "fun_anniversary": {"icon": "🎂", "flavor": "Ein Jahr später, derselbe Weg, ein anderer Läufer — die Reise ehrt ihren Anfang."},
    "fun_bingo": {"icon": "🕐", "flavor": "Die Uhr lacht sich selbst zu — Zufall mit Stil, mehr nicht."},
    "fun_firsts": {"icon": "📅", "flavor": "Sechs Monatserste erobert — Disziplin, die sich den Kalender untertan macht."},
    "fun_ghost": {"icon": "👻", "flavor": "Zwischen Mitternacht und Morgengrauen gelaufen — nur Geister und Legenden sind um diese Zeit wach."},
    "fun_halloween": {"icon": "🎃", "flavor": "Ein Lauf im Schein geschnitzter Kürbisse — die Nacht gehört den Mutigen, nicht den Zombies."},
    "fun_holiday": {"icon": "🎉", "flavor": "Während andere ruhen, läuft er weiter — Feiertage sind für Gewöhnliche."},
    "fun_leap": {"icon": "🐸", "flavor": "Ein Tag, der nur alle vier Jahre existiert — wer ihn erwischt, hat die Zeit selbst überlistet."},
    "fun_midnight": {"icon": "🕛", "flavor": "Genau im Herzschlag zwischen den Tagen gelaufen — die Zeit selbst hielt kurz den Atem an."},
    "fun_moon": {"icon": "🌕", "flavor": "Im silbernen Licht des Vollmonds gelaufen — manche Legenden brauchen keine Sonne."},
    "fun_neujahr": {"icon": "🥂", "flavor": "Der erste Schritt des neuen Jahres war ein Laufschritt – Vorsätze sofort eingelöst."},
    "fun_pacepal": {"icon": "🔢", "flavor": "Ein Tempo, das vor- wie rückwärts gleich bleibt — Symmetrie, die selbst Mathematiker neidisch macht."},
    "fun_palindrome": {"icon": "🔁", "flavor": "Ein Datum, das sich selbst spiegelt — Schrott für die meisten, aber hübsch anzusehen."},
    "fun_silvester": {"icon": "🎇", "flavor": "Zwischen Rückblick und Feuerwerk noch schnell gelaufen – das Jahr endet in Bewegung."},
    "fun_sommer": {"icon": "☀️", "flavor": "Am längsten Tag des Jahres lief er der Sonne davon und gewann trotzdem."},
    "fun_valentin": {"icon": "💌", "flavor": "Ein Lauf am Valentinstag – die Liebe zum Sport braucht keinen Blumenstrauß."},
    "fun_winter": {"icon": "❄️", "flavor": "Kürzester Tag, längster Wille — wer bei Dunkelheit läuft, fürchtet kein Licht."},
    "fun_yearcombo": {"icon": "🎆", "flavor": "Letzter Schritt des alten Jahres, erster des neuen — kein Feuerwerk übertönt diese Entschlossenheit."},
    "hr_calm": {"icon": "🍃", "flavor": "Fünf Läufe im Schatten des eigenen Sturms – die Gelassenheit eines Blattes, das den Wind kennt und ihm vertraut."},
    "hr_decouple": {"icon": "⚙️", "flavor": "Herz und Tempo, im Gleichschritt geschmiedet – ein Uhrwerk, das auch unter Last nicht aus dem Takt gerät."},
    "hr_diet": {"icon": "🥗", "flavor": "Zehn Schläge abgespeckt bei gleichem Tempo – die edelste Diät, die kein Kaloriendefizit kennt."},
    "hr_giant": {"icon": "🗿", "flavor": "Der Berg atmet ruhig, während er wandert – so wandelt auch dieser Läufer, unerschütterlich gelassen."},
    "hr_iron": {"icon": "🛡️", "flavor": "Zehn Kilometer, ruhiges Herz – ein Schild aus eisernem Gleichmut."},
    "hr_lowdrift_long": {"icon": "🏔️", "flavor": "Neunzig Minuten, ein Puls wie Fels. Selbst die Zeit findet keinen Riss in dieser Fassade."},
    "hr_maxpr": {"icon": "⚡", "flavor": "Ein Blitz durch die Adern – ein neuer Gipfel, den das Herz zuvor nie erklommen hat."},
    "hr_neg": {"icon": "🌙", "flavor": "Wenn andere ausbrennen, kühlt dieses Herz weiter ab – ein Lauf, der leiser endet als er begann."},
    "hr_neg_series": {"icon": "🧊", "flavor": "Dreimal in Folge kälter als das Feuer im Blut – die Eisader zieht sich durch drei Läufe ungebrochen."},
    "hr_redzone": {"icon": "🔥", "flavor": "An der Schwelle zum Limit getanzt, im Schatten des eigenen Maximums – wer hier steht, spielt mit dem Feuer."},
    "hr_reserve": {"icon": "📈", "flavor": "Die Spanne zwischen Ruhe und Rausch wächst – ein Reservoir an Kraft, das sich Woche für Woche weitet."},
    "hr_spurt": {"icon": "🚀", "flavor": "175 Schläge und kein Zurück – der Endspurt, bei dem das Herz kurz die Schallmauer streift."},
    "hr_steel": {"icon": "🩶", "flavor": "Fünf Kilometer bei kaum schlagendem Puls – ein Herz aus gehärtetem Stahl."},
    "hr_zoneweek": {"icon": "🌈", "flavor": "Vier Zonen, ein Wille. Der Kartograph des eigenen Pulses zeichnet die volle Skala in nur sieben Tagen."},
    "hrs_100": {"icon": "🌟", "flavor": "Hundert Stunden pure Bewegung – ein legendärer Beweis eiserner Disziplin."},
    "hrs_200": {"icon": "👑", "flavor": "Ein Artefakt der Zeit selbst – zweihundert Stunden im Dienst der eigenen Legende."},
    "hrs_24": {"icon": "🕰️", "flavor": "Ein voller Tag, verbracht im Takt der eigenen Schritte."},
    "hrs_50": {"icon": "⏳", "flavor": "Der Sand rinnt, die Beine tragen – ein ungewöhnliches Maß an Beharrlichkeit."},
    "m_rebound": {"icon": "🌱", "flavor": "Nach der Talsohle ein Sprung nach vorn – Rückschläge sind nur Zwischenstopps."},
    "m_rise3": {"icon": "📈", "flavor": "Drei Monate in Folge mehr – der Trend zeigt nach oben, und er meint es ernst."},
    "m_yoy": {"icon": "⚡", "flavor": "Ein Jahr später, ein Drittel stärker – der Vergleich mit sich selbst gewonnen."},
    "meta_10": {"icon": "🏅", "flavor": "Zehn Trophäen im Regal – der Anfang einer Sammlung, die noch wachsen will."},
    "meta_100": {"icon": "👑", "flavor": "Einhundert Erfolge – eine Legende, von der andere Läufer nur flüstern."},
    "meta_25": {"icon": "🎖️", "flavor": "Fünfundzwanzig Erfolge – aus Gelegenheitsjäger wird ernsthafter Sammler."},
    "meta_50": {"icon": "🏆", "flavor": "Fünfzig Trophäen – dein Schrein für Ausdauer wird langsam zu klein."},
    "meta_cat_serie": {"icon": "🔗", "flavor": "Alle Serien-Erfolge errungen – eine Kette aus Beständigkeit, die niemand zerreißt."},
    "meta_cat_tempo": {"icon": "🌪️", "flavor": "Alle Tempo-Erfolge gemeistert – die Uhr selbst hat vor dir Respekt."},
    "meta_complete": {"icon": "🔥", "flavor": "Alle Erfolge freigeschaltet – ein Mythos, den selbst die Chronisten für unmöglich hielten."},
    "meta_pts_1000": {"icon": "🪙", "flavor": "Tausend Punkte gesammelt – die ersten Münzen im Schatzbeutel des Ausdauerhelden."},
    "meta_pts_3000": {"icon": "💰", "flavor": "Dreitausend Punkte – der Beutel wird schwer, der Ehrgeiz schwerer."},
    "meta_pts_6000": {"icon": "💎", "flavor": "Sechstausend Punkte – ein Schatz, den nur die Hartnäckigsten je heben."},
    "meta_sameday": {"icon": "⚡", "flavor": "Drei Erfolge an einem Tag – als hätte das Schicksal gleich dreimal applaudiert."},
    "meta_variety": {"icon": "🧭", "flavor": "Ein Erfolg aus jeder Kategorie – das Abzeichen derer, die keinen Pfad ausließen."},
    "month_king": {"icon": "🎖️", "flavor": "Schnellster Lauf des Monats – kurz auf dem Thron, lange in Erinnerung."},
    "month_record": {"icon": "📈", "flavor": "Ein neuer Gipfel im Distanz-Diagramm. Der alte Monat verneigt sich vor dir."},
    "month_streak_12": {"icon": "🌟", "flavor": "Zwölf Monate, jeder mit mindestens einem Lauf. Ein Jahr ohne Lücke — das schreibt man sich auf die Fahne."},
    "month_streak_6": {"icon": "🌙", "flavor": "Sechs Monate ohne Fehlmonat — Beständigkeit, die selbst der Winter nicht bricht."},
    "pr_broken": {"icon": "📈", "flavor": "Ein alter Rekord fällt – die Geschichtsbücher werden neu geschrieben."},
    "pr_trophyroom": {"icon": "🏆", "flavor": "Fünf Distanzen, fünf Trophäen – dein Schrank glänzt wie eine Ahnenhalle."},
    "season_solid": {"icon": "🏔️", "flavor": "13 Wochen einer Saison, jede einzelne bestritten – ein Fels, den kein Wetter erschüttert."},
    "seasons_ever": {"icon": "🍂", "flavor": "Frühling, Sommer, Herbst und Winter – du hast sie alle unter den Sohlen gehabt."},
    "seasons_year": {"icon": "🍃", "flavor": "Ein Jahr, vier Jahreszeiten, keine Pause – der Kreislauf komplett durchlaufen."},
    "sp_early": {"icon": "🌅", "flavor": "Vor dem ersten Sonnenstrahl unterwegs — die Faulen schlafen, die Legenden laufen."},
    "sp_night": {"icon": "🌙", "flavor": "Wenn andere den Tag beenden, beginnt seiner erst richtig."},
    "sp_weekend": {"icon": "⚔️", "flavor": "Zwei Tage, ein Wille — das Wochenende kapituliert vor echter Hartnäckigkeit."},
    "spd10_3000": {"icon": "👑", "flavor": "10 km unter 50 Minuten – eine Krone, die nur wenige Stirnen tragen."},
    "spd10_3300": {"icon": "💎", "flavor": "55 Minuten auf 10 km – geschliffen wie ein Edelstein aus reiner Ausdauer."},
    "spd10_3600": {"icon": "🥇", "flavor": "Zehn Kilometer unter der Stunde – der Asphalt verbeugt sich."},
    "spd15": {"icon": "🏔️", "flavor": "15 Kilometer unter 90 Minuten – ein Gebirgspass, den nur Zähigkeit überwindet."},
    "spd1_270": {"icon": "🚀", "flavor": "Manche Läufer laufen. Du wirst abgefeuert."},
    "spd1_300": {"icon": "⚡", "flavor": "Ein Kilometer, ein Blitz – die Sohlen glühen unter dir."},
    "spd1_330": {"icon": "🍃", "flavor": "Der Wind merkt sich langsam deinen Namen."},
    "spd1_360": {"icon": "👟", "flavor": "Ein solider Schuhabtritt für Anfänger – kein Ruhm, aber kein Stolpern."},
    "spd20": {"icon": "🗻", "flavor": "20 Kilometer unter zwei Stunden – der lange Marsch der Willensstarken."},
    "spd5_1500": {"icon": "🔥", "flavor": "25 Minuten für 5 Kilometer – ein Brandzeichen für Legenden im Werden."},
    "spd5_1650": {"icon": "🌀", "flavor": "27:30 – dein Puls und deine Uhr streiten sich, wer schneller tickt."},
    "spd5_1800": {"icon": "🥾", "flavor": "Fünf Kilometer unter der Dreißig-Minuten-Schallmauer – der Einstieg in die Liga der Ernsthaften."},
    "tm_100": {"icon": "🎡", "flavor": "Ein Hamsterrad-Held im besten Sinne – hundert Kilometer, nirgendwo hin, überallhin gewachsen."},
    "tm_250": {"icon": "🌀", "flavor": "Wer dem Laufband so treu bleibt, verdient einen Platz in der seltenen Halle der Ausdauer."},
    "total_100": {"icon": "🌱", "flavor": "Aus dem Gehölz der Anfänger wächst der erste zarte Trieb der Ausdauer."},
    "total_1000": {"icon": "🏔️", "flavor": "Ein Artefakt der Ausdauer, geschmiedet aus tausend Kilometern Schweiß und Sturheit."},
    "total_10000": {"icon": "⚡", "flavor": "Mythos-Distanz. Wer hier ankommt, hat die Sterblichkeit hinter sich gelassen."},
    "total_2000": {"icon": "🗿", "flavor": "Uralte Meilensteine erzählen von Läufern, die die Erde zweimal umrundet zu haben scheinen."},
    "total_25": {"icon": "👟", "flavor": "Schrott? Vielleicht. Aber jede Legende begann mit einem müden ersten Schritt."},
    "total_250": {"icon": "🔷", "flavor": "Ein seltener Pfad durchs Unterholz – nicht jeder findet ihn, wer läuft, schon."},
    "total_3000": {"icon": "🌋", "flavor": "Ein Titanenwerk – manche Läufer werden zu wandelnden Sagen."},
    "total_50": {"icon": "🥾", "flavor": "Die Sohlen kennen jetzt deinen Namen."},
    "total_500": {"icon": "🔥", "flavor": "Legendäres Feuer im Wadenmuskel – halbe Tausend, ganze Hingabe."},
    "total_5000": {"icon": "🐉", "flavor": "Ein Drache unter den Erfolgen – gesichtet, aber kaum je erlegt."},
    "total_marathons25": {"icon": "🏛️", "flavor": "Fünfundzwanzigmal die Strecke des Pheidippides – die Götter nicken anerkennend."},
    "vo2_pr": {"icon": "🫁", "flavor": "Deine Lunge hat sich einen neuen Bestwert erarbeitet — Sauerstoff, effizient wie nie."},
    "wallround": {"icon": "🎲", "flavor": "An fünf Tagen zugeschlagen. Kein Wochentag ist vor dir sicher."},
    "wd_ritual": {"icon": "🕰️", "flavor": "Sechs Wochen, derselbe Wochentag — ein Ritual, das sich in den Kalender eingebrannt hat."},
    "wdbl_long": {"icon": "🌓", "flavor": "Zwei Langläufe, eine Marathon-Summe – zweimal Mondlicht am Horizont der Erschöpfung."},
    "wdur_5h": {"icon": "⏳", "flavor": "5 Stunden im Fluss der Bewegung – Zeit wird zur Nebensache, Ausdauer zur Hauptsache."},
    "weeks_100": {"icon": "📆", "flavor": "Hundert Wochen im Schatten der Regelmäßigkeit. Nicht spektakulär, aber unaufhaltsam."},
    "wk_10of12": {"icon": "🛡️", "flavor": "Zehn von zwölf Wochen gehalten, trotz allem. Nicht makellos, aber unerschütterlich."},
    "wk_in_month": {"icon": "🗝️", "flavor": "Jede Woche des Monats mit Laufschuhen besiegelt – Lücken? Nicht diesmal."},
    "wk_no2zero": {"icon": "⚖️", "flavor": "26 Wochen, nie zwei Nuller hintereinander — das Gleichgewicht eines Kriegers, der nie ganz stillsteht."},
    "wk_streak_12": {"icon": "🗓️", "flavor": "Ein ganzes Quartal treu gelaufen. Das ist kein Zufallstreffer mehr, das ist Charakter."},
    "wk_streak_26": {"icon": "🌗", "flavor": "Ein halbes Jahr ohne Lücke — die Trittfrequenz ist längst zur zweiten Natur geworden."},
    "wk_streak_4": {"icon": "📅", "flavor": "Vier Wochen, keine Ausrede. Ein solider Anfang, mehr Blechkette als Amulett — aber ehrlich verdient."},
    "wk_streak_52": {"icon": "🏆", "flavor": "Zwölf Monate, keine Nullwoche. Die Chroniken werden von wenigen so geschrieben."},
    "wk_streak_8": {"icon": "🥾", "flavor": "Acht Wochen am Stück — die Schuhe kennen den Weg inzwischen auswendig."},
    "wkm_100": {"icon": "🏔️", "flavor": "100 km in sieben Tagen. Die Götter des Ausdauersports nicken anerkennend."},
    "wkm_20": {"icon": "👟", "flavor": "20 Kilometer – der erste Beweis, dass die Laufschuhe kein Deko-Objekt sind."},
    "wkm_30": {"icon": "🍃", "flavor": "30 km in einer Woche. Der Wind kennt jetzt deinen Namen."},
    "wkm_40": {"icon": "⚡", "flavor": "40 km – die Straße knistert unter deinen Schritten wie geladene Luft."},
    "wkm_50": {"icon": "🔥", "flavor": "50 Kilometer Wochenfeuer. Die Asphalt-Legenden erzählen sich schon von dir."},
    "wkm_75": {"icon": "🌪️", "flavor": "75 km – ein Wirbelsturm aus Ehrgeiz, der ganze Wochen in Fußabdrücke verwandelt."},
    "wrun_3": {"icon": "🔺", "flavor": "Dreimal die Woche unterwegs – die Dreifaltigkeit der Trainingsroutine."},
    "wrun_4": {"icon": "🍀", "flavor": "Viermal in einer Woche – das Glück des Fleißigen kennt keine Pause."},
    "wrun_5": {"icon": "🗓️", "flavor": "Fünf Tage, fünf Läufe. Die Woche zittert vor dir wie ein Rekrut vorm Feldwebel."},
    "y_allmonths": {"icon": "🗓️", "flavor": "Kein Monat blieb verschont – zwölf Kapitel derselben unaufhaltsamen Geschichte."},
    "y_allweeks": {"icon": "👑", "flavor": "52 Wochen, null Ausreden – die Chronik eines Jahres ohne eine einzige Lücke."},
    "y_end_km": {"icon": "🎆", "flavor": "Die letzte Jahreswoche noch einmal volle Kraft – kein Ausklingen, sondern ein Finale."},
    "y_quarters": {"icon": "🧭", "flavor": "Vier Quartale, jedes mit Substanz – Beständigkeit schlägt Strohfeuer."},
    "y_start_km": {"icon": "🌅", "flavor": "Die erste Woche des Jahres schon mit Ansage begonnen – so kündigt man Großes an."},
    "ykm_1000": {"icon": "🐉", "flavor": "1000 km in zwölf Monaten – eine Leistung, von der andere nur beim Aufwärmen träumen."},
    "ykm_500": {"icon": "🔮", "flavor": "500 Kilometer, in einem Jahr verbrannt – ein solides Fundament aus Schweiß und Sturheit."},
    "zone_collector": {"icon": "🌈", "flavor": "Alle vier Pulszonen erobert – vom gemütlichen Plausch-Tempo bis zum keuchenden Vollgas."},
}
