// 100 witzige Lade-Sprüche für den „Coach denkt nach"-Moment.
// Rotieren alle paar Sekunden, während der LLM-Coach seine Tools abklappert.
export const COACH_QUIPS: string[] = [
  "Zähle deine Wiederholungen nach",
  "Überrede die Hanteln, leichter zu wirken",
  "Frage deine Oberschenkel um Erlaubnis",
  "Suche nach versteckten Gains",
  "Poliere deine Bestleistungen",
  "Sortiere die Sätze nach Anstrengung",
  "Lege noch eine Scheibe auf",
  "Verhandle mit dem Muskelkater",
  "Interpoliere deinen Schweiß",
  "Trianguliere deine Fortschritte",
  "Glätte die Ausreißer weg",
  "Rechne dein Defizit schön",
  "Befrage die Datenbank höflich",
  "Korreliere Kraft und Kaffee",
  "Entwirre die Trendlinien",
  "Normalisiere deine Ambitionen",
  "Kalibriere die gute Laune",
  "Wiege das letzte Gramm Protein",
  "Bestiche die Waage",
  "Versteck die Kekse vor dir selbst",
  "Zähle die Makros zur Sicherheit zweimal",
  "Diskutiere mit dem Kühlschrank",
  "Runde die Kalorien wohlwollend",
  "Suche nach Ausreden – und ignoriere sie",
  "Erfinde eine neue Bestleistung",
  "Pumpe die Pixel auf",
  "Dehne die Zeitachse",
  "Streichle den Algorithmus",
  "Frag die Galaxy Watch nach dem Wetter",
  "Bügle die Trendkurve glatt",
  "Hol die schweren Zahlen aus dem Keller",
  "Lass die Tonnage Anlauf nehmen",
  "Schick die Daten zum Aufwärmen",
  "Verbeuge mich vor deinem Trizeps",
  "Stapel die Gewichte ordentlich",
  "Atme tief ein für die Auswertung",
  "Wecke die schlafenden Statistiken",
  "Politur für den e1RM",
  "Frage die Beinpresse nach Geheimnissen",
  "Zähl die Schritte – jeden einzelnen",
  "Lass den Index Klimmzüge machen",
  "Massiere die Datenpunkte",
  "Spann den Bizeps für die Kamera an",
  "Sortiere Schweißtropfen nach Größe",
  "Lade die Motivation … 87 %",
  "Suche dein zweites Frühstück",
  "Frag das Defizit, ob es Hunger hat",
  "Spitze die Bleistifte für die Mathematik",
  "Häng die Bestleistungen an die Wand",
  "Verhandle einen Ruhetag (abgelehnt)",
  "Beruhige die nervösen Kurven",
  "Zähle deine Liegestütze von gestern",
  "Wische den Staub von alten Rekorden",
  "Frage die Wade, warum sie zwickt",
  "Sammle verstreute Protokollzeilen ein",
  "Lass die KI ein paar Sätze drücken",
  "Putze die Brille für die Feinanalyse",
  "Heb die Stimmung – sauber aus den Knien",
  "Stell die Uhr auf Bestzeit",
  "Schraub die Erwartungen fest",
  "Zieh die Trendlinie gerade",
  "Frag die Hantelbank um Rat",
  "Wärm die Kommazahlen vor",
  "Such den Rhythmus im Chaos",
  "Klopf den Muskeln auf die Schulter",
  "Misch die Makros zu einem Smoothie",
  "Zähl die Wochen rückwärts",
  "Lass die Schritte Schlange stehen",
  "Frag das Cardio, ob es noch lebt",
  "Stemm die letzte Berechnung hoch",
  "Justiere die Zielgerade",
  "Streck die Faulheit aus dem System",
  "Sortiere PRs nach Stolz",
  "Bürste die VO₂max auf Hochglanz",
  "Frag die Daten nett: „Na, wie läuft's?“",
  "Lade frischen Ehrgeiz nach",
  "Klär das Missverständnis mit der Waage",
  "Zähle Kalorien wie Schäfchen",
  "Heb die Augenbrauen über die Tonnage",
  "Lass den Puls kurz angeben",
  "Schick die Ausreden in die Mittagspause",
  "Knete die Zahlen weich",
  "Hol Anlauf für die Pointe",
  "Spann das Maßband nach",
  "Frag den Schlaf, ob er ausgeschlafen hat",
  "Sortiere die Gewichte nach Laune",
  "Wickel die Trendlinie um den Finger",
  "Zähl die Tropfen im Eimer",
  "Stell dem Defizit ein Bein",
  "Poliere die Statistik, bis sie glänzt",
  "Lass die Bytes ein paar Burpees machen",
  "Frag die Muskeln nach ihrer Tagesform",
  "Kalibriere den Optimismus neu",
  "Sortiere die Wahrheit von den Wunschwerten",
  "Spitz die Pointe für den Schluss",
  "Such den Silberstreif in der Tonnage",
  "Lass die Zahlen einmal durchatmen",
  "Verhandle mit der Schwerkraft (zäh)",
  "Schnür dem Coach noch die Laufschuhe",
  "Gleich hast du's – letzte Sätze laufen",
];
